In [20]:
import numpy as np

A = np.full((2,3),2)
A[1,:] = 1
B = np.diag([1,2,3])

A, B , A.shape, B.shape

(array([[2, 2, 2],
        [1, 1, 1]]),
 array([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]]),
 (2, 3),
 (3, 3))

In [35]:
A@B

tensor([[2., 4., 6.],
        [1., 2., 3.]])

In [26]:
# multiplication for loop
mult = np.zeros((A.shape[0],B.shape[1]))

for i in range(A.shape[0]):
    for j in range(B.shape[1]):

        for k in range(A.shape[1]):
            mult[i,j] += A[i,k] * B[k,j]

C = np.zeros(B.shape[1])
for j in range(B.shape[1]):
    C[j] = sum(mult[:,j])

C

array([3., 6., 9.])

In [29]:
np.sum(A@B,axis=0)

array([12,  6])

in einsum:

$$
c_{j} = A_{ik} B_{kj} 
$$

In [32]:
import torch

In [36]:
A = torch.tensor([[2,2,2],[1,1,1]],dtype=torch.float32)
B = torch.tensor([[1,0,0],[0,2,0],[0,0,3]],dtype=torch.float32)

torch.einsum('ik,kj->j',A,B)

tensor([3., 6., 9.])

lets try more operations

In [41]:
torch.einsum('ij->ji',A)

tensor([[2., 1.],
        [2., 1.],
        [2., 1.]])

In [43]:
torch.einsum('ij->',A)

tensor(9.)

In [45]:
torch.einsum('ij->j',A)

tensor([3., 3., 3.])

In [48]:
torch.einsum('ij->i',A)

tensor([6., 3.])

In [49]:
vector = torch.tensor([1,2,3],dtype=torch.float32)

torch.einsum('ik,k->i',A,vector)

tensor([12.,  6.])

In [65]:
a = torch.arange(3)
b = torch.arange(3,6)  # -- a vector of length 3 containing [3, 4, 5]

torch.einsum('i,i->', a, b)

tensor(14)

In [68]:
sum(a*b)

tensor(14)

In [73]:
a = torch.randn(3,2,5)
b = torch.randn(3,5,3)

# Batch Matrix Multiplication
torch.einsum('bik,bkj->bij', [a, b]).shape


torch.Size([3, 2, 3])

In [81]:
# check if equals to a@b
sum(sum(sum(torch.einsum('bik,bkj->bij', [a, b]) - a@b)))

# this is equals to:

torch.einsum('bij->', torch.einsum('bik,bkj->bij', [a, b]) - a@b)

tensor(0.)

tensor(0.)